version: "3.7"

services: 
  database_auth:
    image: postgres
    container_name: database_auth
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=auth
      - POSTGRES_DB=auth
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: auth
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database_auth
    depends_on: 
      - database_auth

volumes: 
  pgdata: 
    driver: local
  